# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Role.delete_all
# ActiveRecord::Base.connection.execute("ALTER SEQUENCE roles_id_seq RESTART WITH 1;")
# Role.create(:name => "Super Admin", :status => "1")
# Role.create(:name => "Administrator", :status => "1")
# Role.create(:name => "Manager", :status => "1")
# 
# User.delete_all
# ActiveRecord::Base.connection.execute("ALTER SEQUENCE users_id_seq RESTART WITH 1;")
# User.create(:email => "developer@vidanutriscience.com", :password => "digiteervidanutriscience", :first_name => "Vida Nutriscience", :last_name => "Super Admin", :role_id => 1)
# 
# Slider.delete_all
# ActiveRecord::Base.connection.execute("ALTER SEQUENCE sliders_id_seq RESTART WITH 1;")
# Slider.create(:title => "Slider One", :status => "0")
# Slider.create(:title => "Slider Two", :status => "0")
# Slider.create(:title => "Slider Three", :status => "0")
# Slider.create(:title => "Slider Four", :status => "0")
# Slider.create(:title => "Slider Five", :status => "0")
# Slider.create(:title => "Slider Six", :status => "0")
# 
# Country.delete_all
# ActiveRecord::Base.connection.execute("ALTER SEQUENCE countries_id_seq RESTART WITH 1;")
# Country.create(:name => "Afghanistan", :code => "AF", :status => "1")
# Country.create(:name => "Aland Islands", :code => "AX", :status => "1")
# Country.create(:name => "Albania", :code => "AL", :status => "1")
# Country.create(:name => "Algeria", :code => "DZ", :status => "1")
# Country.create(:name => "American Samoa", :code => "AS", :status => "1")
# Country.create(:name => "Andorra", :code => "AD", :status => "1")
# Country.create(:name => "Angola", :code => "AO", :status => "1")
# Country.create(:name => "Anguilla", :code => "AI", :status => "1")
# Country.create(:name => "Antarctica", :code => "AQ", :status => "1")
# Country.create(:name => "Antigua and Barbuda", :code => "AG", :status => "1")
# Country.create(:name => "Argentina", :code => "AR", :status => "1")
# Country.create(:name => "Armenia", :code => "AM", :status => "1")
# Country.create(:name => "Aruba", :code => "AW", :status => "1")
# Country.create(:name => "Australia", :code => "AU", :status => "1")
# Country.create(:name => "Austria", :code => "AT", :status => "1")
# Country.create(:name => "Azerbaijan", :code => "AZ", :status => "1")
# Country.create(:name => "Bahamas", :code => "BS", :status => "1")
# Country.create(:name => "Bahrain", :code => "BH", :status => "1")
# Country.create(:name => "Bangladesh", :code => "BD", :status => "1")
# Country.create(:name => "Barbados", :code => "BB", :status => "1")
# Country.create(:name => "Belarus", :code => "BY", :status => "1")
# Country.create(:name => "Belgium", :code => "BE", :status => "1")
# Country.create(:name => "Belize", :code => "BZ", :status => "1")
# Country.create(:name => "Benin", :code => "BJ", :status => "1")
# Country.create(:name => "Bermuda", :code => "BM", :status => "1")
# Country.create(:name => "Bhutan", :code => "BT", :status => "1")
# Country.create(:name => "Bolivia, Plurinational State of", :code => "BO", :status => "1")
# Country.create(:name => "Bonaire, Sint Eustatius and Saba", :code => "BQ", :status => "1")
# Country.create(:name => "Bosnia and Herzegovina", :code => "BA", :status => "1")
# Country.create(:name => "Botswana", :code => "BW", :status => "1")
# Country.create(:name => "Bouvet Island", :code => "BV", :status => "1")
# Country.create(:name => "Brazil", :code => "BR", :status => "1")
# Country.create(:name => "British Indian Ocean Territory", :code => "IO", :status => "1")
# Country.create(:name => "Brunei Darussalam", :code => "BN", :status => "1")
# Country.create(:name => "Bulgaria", :code => "BG", :status => "1")
# Country.create(:name => "Burkina Faso", :code => "BF", :status => "1")
# Country.create(:name => "Burundi", :code => "BI", :status => "1")
# Country.create(:name => "Cambodia", :code => "KH", :status => "1")
# Country.create(:name => "Cameroon", :code => "CM", :status => "1")
# Country.create(:name => "Canada", :code => "CA", :status => "1")
# Country.create(:name => "Cape Verde", :code => "CV", :status => "1")
# Country.create(:name => "Cayman Islands", :code => "KY", :status => "1")
# Country.create(:name => "Central African Republic", :code => "CF", :status => "1")
# Country.create(:name => "Chad", :code => "TD", :status => "1")
# Country.create(:name => "Chile", :code => "CL", :status => "1")
# Country.create(:name => "China", :code => "CN", :status => "1")
# Country.create(:name => "Christmas Island", :code => "CX", :status => "1")
# Country.create(:name => "Cocos (Keeling) Islands", :code => "CC", :status => "1")
# Country.create(:name => "Colombia", :code => "CO", :status => "1")
# Country.create(:name => "Comoros", :code => "KM", :status => "1")
# Country.create(:name => "Congo", :code => "CG", :status => "1")
# Country.create(:name => "Congo, the Democratic Republic of the", :code => "CD", :status => "1")
# Country.create(:name => "Cook Islands", :code => "CK", :status => "1")
# Country.create(:name => "Costa Rica", :code => "CR", :status => "1")
# Country.create(:name => "Cote d'Ivoire", :code => "CI", :status => "1")
# Country.create(:name => "Croatia", :code => "HR", :status => "1")
# Country.create(:name => "Cuba", :code => "CU", :status => "1")
# Country.create(:name => "Curacao", :code => "CW", :status => "1")
# Country.create(:name => "Cyprus", :code => "CY", :status => "1")
# Country.create(:name => "Czech Republic", :code => "CZ", :status => "1")
# Country.create(:name => "Denmark", :code => "DK", :status => "1")
# Country.create(:name => "Djibouti", :code => "DJ", :status => "1")
# Country.create(:name => "Dominica", :code => "DM", :status => "1")
# Country.create(:name => "Dominican Republic", :code => "DO", :status => "1")
# Country.create(:name => "Ecuador", :code => "EC", :status => "1")
# Country.create(:name => "Egypt", :code => "EG", :status => "1")
# Country.create(:name => "El Salvador", :code => "SV", :status => "1")
# Country.create(:name => "Equatorial Guinea", :code => "GQ", :status => "1")
# Country.create(:name => "Eritrea", :code => "ER", :status => "1")
# Country.create(:name => "Estonia", :code => "EE", :status => "1")
# Country.create(:name => "Ethiopia", :code => "ET", :status => "1")
# Country.create(:name => "Falkland Islands (Malvinas)", :code => "FK", :status => "1")
# Country.create(:name => "Faroe Islands", :code => "FO", :status => "1")
# Country.create(:name => "Fiji", :code => "FJ", :status => "1")
# Country.create(:name => "Finland", :code => "FI", :status => "1")
# Country.create(:name => "France", :code => "FR", :status => "1")
# Country.create(:name => "French Guiana", :code => "GF", :status => "1")
# Country.create(:name => "French Polynesia", :code => "PF", :status => "1")
# Country.create(:name => "French Southern Territories", :code => "TF", :status => "1")
# Country.create(:name => "Gabon", :code => "GA", :status => "1")
# Country.create(:name => "Gambia", :code => "GM", :status => "1")
# Country.create(:name => "Georgia", :code => "GE", :status => "1")
# Country.create(:name => "Germany", :code => "DE", :status => "1")
# Country.create(:name => "Ghana", :code => "GH", :status => "1")
# Country.create(:name => "Gibraltar", :code => "GI", :status => "1")
# Country.create(:name => "Greece", :code => "GR", :status => "1")
# Country.create(:name => "Greenland", :code => "GL", :status => "1")
# Country.create(:name => "Grenada", :code => "GD", :status => "1")
# Country.create(:name => "Guadeloupe", :code => "GP", :status => "1")
# Country.create(:name => "Guam", :code => "GU", :status => "1")
# Country.create(:name => "Guatemala", :code => "GT", :status => "1")
# Country.create(:name => "Guernsey", :code => "GG", :status => "1")
# Country.create(:name => "Guinea", :code => "GN", :status => "1")
# Country.create(:name => "Guinea-Bissau", :code => "GW", :status => "1")
# Country.create(:name => "Guyana", :code => "GY", :status => "1")
# Country.create(:name => "Haiti", :code => "HT", :status => "1")
# Country.create(:name => "Heard Island and McDonald Islands", :code => "HM", :status => "1")
# Country.create(:name => "Holy See (Vatican City State)", :code => "VA", :status => "1")
# Country.create(:name => "Honduras", :code => "HN", :status => "1")
# Country.create(:name => "Hong Kong", :code => "HK", :status => "1")
# Country.create(:name => "Hungary", :code => "HU", :status => "1")
# Country.create(:name => "Iceland", :code => "IS", :status => "1")
# Country.create(:name => "India", :code => "IN", :status => "1")
# Country.create(:name => "Indonesia", :code => "ID", :status => "1")
# Country.create(:name => "Iran, Islamic Republic of", :code => "IR", :status => "1")
# Country.create(:name => "Iraq", :code => "IQ", :status => "1")
# Country.create(:name => "Ireland", :code => "IE", :status => "1")
# Country.create(:name => "Isle of Man", :code => "IM", :status => "1")
# Country.create(:name => "Israel", :code => "IL", :status => "1")
# Country.create(:name => "Italy", :code => "IT", :status => "1")
# Country.create(:name => "Jamaica", :code => "JM", :status => "1")
# Country.create(:name => "Japan", :code => "JP", :status => "1")
# Country.create(:name => "Jersey", :code => "JE", :status => "1")
# Country.create(:name => "Jordan", :code => "JO", :status => "1")
# Country.create(:name => "Kazakhstan", :code => "KZ", :status => "1")
# Country.create(:name => "Kenya", :code => "KE", :status => "1")
# Country.create(:name => "Kiribati", :code => "KI", :status => "1")
# Country.create(:name => "Korea, Democratic People's Republic of", :code => "KP", :status => "1")
# Country.create(:name => "Korea, Republic of", :code => "KR", :status => "1")
# Country.create(:name => "Kuwait", :code => "KW", :status => "1")
# Country.create(:name => "Kyrgyzstan", :code => "KG", :status => "1")
# Country.create(:name => "Lao People's Democratic Republic", :code => "LA", :status => "1")
# Country.create(:name => "Latvia", :code => "LV", :status => "1")
# Country.create(:name => "Lebanon", :code => "LB", :status => "1")
# Country.create(:name => "Lesotho", :code => "LS", :status => "1")
# Country.create(:name => "Liberia", :code => "LR", :status => "1")
# Country.create(:name => "Libya", :code => "LY", :status => "1")
# Country.create(:name => "Liechtenstein", :code => "LI", :status => "1")
# Country.create(:name => "Lithuania", :code => "LT", :status => "1")
# Country.create(:name => "Luxembourg", :code => "LU", :status => "1")
# Country.create(:name => "Macao", :code => "MO", :status => "1")
# Country.create(:name => "Macedonia, the Former Yugoslav Republic of", :code => "MK", :status => "1")
# Country.create(:name => "Madagascar", :code => "MG", :status => "1")
# Country.create(:name => "Malawi", :code => "MW", :status => "1")
# Country.create(:name => "Malaysia", :code => "MY", :status => "1")
# Country.create(:name => "Maldives", :code => "MV", :status => "1")
# Country.create(:name => "Mali", :code => "ML", :status => "1")
# Country.create(:name => "Malta", :code => "MT", :status => "1")
# Country.create(:name => "Marshall Islands", :code => "MH", :status => "1")
# Country.create(:name => "Martinique", :code => "MQ", :status => "1")
# Country.create(:name => "Mauritania", :code => "MR", :status => "1")
# Country.create(:name => "Mauritius", :code => "MU", :status => "1")
# Country.create(:name => "Mayotte", :code => "YT", :status => "1")
# Country.create(:name => "Mexico", :code => "MX", :status => "1")
# Country.create(:name => "Micronesia, Federated States of", :code => "FM", :status => "1")
# Country.create(:name => "Moldova, Republic of", :code => "MD", :status => "1")
# Country.create(:name => "Monaco", :code => "MC", :status => "1")
# Country.create(:name => "Mongolia", :code => "MN", :status => "1")
# Country.create(:name => "Montenegro", :code => "ME", :status => "1")
# Country.create(:name => "Montserrat", :code => "MS", :status => "1")
# Country.create(:name => "Morocco", :code => "MA", :status => "1")
# Country.create(:name => "Mozambique", :code => "MZ", :status => "1")
# Country.create(:name => "Myanmar", :code => "MM", :status => "1")
# Country.create(:name => "Namibia", :code => "NA", :status => "1")
# Country.create(:name => "Nauru", :code => "NR", :status => "1")
# Country.create(:name => "Nepal", :code => "NP", :status => "1")
# Country.create(:name => "Netherlands", :code => "NL", :status => "1")
# Country.create(:name => "New Caledonia", :code => "NC", :status => "1")
# Country.create(:name => "New Zealand", :code => "NZ", :status => "1")
# Country.create(:name => "Nicaragua", :code => "NI", :status => "1")
# Country.create(:name => "Niger", :code => "NE", :status => "1")
# Country.create(:name => "Nigeria", :code => "NG", :status => "1")
# Country.create(:name => "Niue", :code => "NU", :status => "1")
# Country.create(:name => "Norfolk Island", :code => "NF", :status => "1")
# Country.create(:name => "Northern Mariana Islands", :code => "MP", :status => "1")
# Country.create(:name => "Norway", :code => "NO", :status => "1")
# Country.create(:name => "Oman", :code => "OM", :status => "1")
# Country.create(:name => "Pakistan", :code => "PK", :status => "1")
# Country.create(:name => "Palau", :code => "PW", :status => "1")
# Country.create(:name => "Palestine, State of", :code => "PS", :status => "1")
# Country.create(:name => "Panama", :code => "PA", :status => "1")
# Country.create(:name => "Papua New Guinea", :code => "PG", :status => "1")
# Country.create(:name => "Paraguay", :code => "PY", :status => "1")
# Country.create(:name => "Peru", :code => "PE", :status => "1")
# Country.create(:name => "Philippines", :code => "PH", :status => "1")
# Country.create(:name => "Pitcairn", :code => "PN", :status => "1")
# Country.create(:name => "Poland", :code => "PL", :status => "1")
# Country.create(:name => "Portugal", :code => "PT", :status => "1")
# Country.create(:name => "Puerto Rico", :code => "PR", :status => "1")
# Country.create(:name => "Qatar", :code => "QA", :status => "1")
# Country.create(:name => "Reunion", :code => "RE", :status => "1")
# Country.create(:name => "Romania", :code => "RO", :status => "1")
# Country.create(:name => "Russian Federation", :code => "RU", :status => "1")
# Country.create(:name => "Rwanda", :code => "RW", :status => "1")
# Country.create(:name => "Saint Barthelemy", :code => "BL", :status => "1")
# Country.create(:name => "Saint Helena, Ascension and Tristan da Cunha", :code => "SH", :status => "1")
# Country.create(:name => "Saint Kitts and Nevis", :code => "KN", :status => "1")
# Country.create(:name => "Saint Lucia", :code => "LC", :status => "1")
# Country.create(:name => "Saint Martin (French part)", :code => "MF", :status => "1")
# Country.create(:name => "Saint Pierre and Miquelon", :code => "PM", :status => "1")
# Country.create(:name => "Saint Vincent and the Grenadines", :code => "VC", :status => "1")
# Country.create(:name => "Samoa", :code => "WS", :status => "1")
# Country.create(:name => "San Marino", :code => "SM", :status => "1")
# Country.create(:name => "Sao Tome and Principe", :code => "ST", :status => "1")
# Country.create(:name => "Saudi Arabia", :code => "SA", :status => "1")
# Country.create(:name => "Senegal", :code => "SN", :status => "1")
# Country.create(:name => "Serbia", :code => "RS", :status => "1")
# Country.create(:name => "Seychelles", :code => "SC", :status => "1")
# Country.create(:name => "Sierra Leone", :code => "SL", :status => "1")
# Country.create(:name => "Singapore", :code => "SG", :status => "1")
# Country.create(:name => "Sint Maarten (Dutch part)", :code => "SX", :status => "1")
# Country.create(:name => "Slovakia", :code => "SK", :status => "1")
# Country.create(:name => "Slovenia", :code => "SI", :status => "1")
# Country.create(:name => "Solomon Islands", :code => "SB", :status => "1")
# Country.create(:name => "Somalia", :code => "SO", :status => "1")
# Country.create(:name => "South Africa", :code => "ZA", :status => "1")
# Country.create(:name => "South Georgia and the South Sandwich Islands", :code => "GS", :status => "1")
# Country.create(:name => "South Sudan", :code => "SS", :status => "1")
# Country.create(:name => "Spain", :code => "ES", :status => "1")
# Country.create(:name => "Sri Lanka", :code => "LK", :status => "1")
# Country.create(:name => "Sudan", :code => "SD", :status => "1")
# Country.create(:name => "Suriname", :code => "SR", :status => "1")
# Country.create(:name => "Svalbard and Jan Mayen", :code => "SJ", :status => "1")
# Country.create(:name => "Swaziland", :code => "SZ", :status => "1")
# Country.create(:name => "Sweden", :code => "SE", :status => "1")
# Country.create(:name => "Switzerland", :code => "CH", :status => "1")
# Country.create(:name => "Syrian Arab Republic", :code => "SY", :status => "1")
# Country.create(:name => "Taiwan, Province of China", :code => "TW", :status => "1")
# Country.create(:name => "Tajikistan", :code => "TJ", :status => "1")
# Country.create(:name => "Tanzania, United Republic of", :code => "TZ", :status => "1")
# Country.create(:name => "Thailand", :code => "TH", :status => "1")
# Country.create(:name => "Timor-Leste", :code => "TL", :status => "1")
# Country.create(:name => "Togo", :code => "TG", :status => "1")
# Country.create(:name => "Tokelau", :code => "TK", :status => "1")
# Country.create(:name => "Tonga", :code => "TO", :status => "1")
# Country.create(:name => "Trinidad and Tobago", :code => "TT", :status => "1")
# Country.create(:name => "Tunisia", :code => "TN", :status => "1")
# Country.create(:name => "Turkey", :code => "TR", :status => "1")
# Country.create(:name => "Turkmenistan", :code => "TM", :status => "1")
# Country.create(:name => "Turks and Caicos Islands", :code => "TC", :status => "1")
# Country.create(:name => "Tuvalu", :code => "TV", :status => "1")
# Country.create(:name => "Uganda", :code => "UG", :status => "1")
# Country.create(:name => "Ukraine", :code => "UA", :status => "1")
# Country.create(:name => "United Arab Emirates", :code => "AE", :status => "1")
# Country.create(:name => "United Kingdom", :code => "GB", :status => "1")
# Country.create(:name => "United States", :code => "US", :status => "1")
# Country.create(:name => "United States Minor Outlying Islands", :code => "UM", :status => "1")
# Country.create(:name => "Uruguay", :code => "UY", :status => "1")
# Country.create(:name => "Uzbekistan", :code => "UZ", :status => "1")
# Country.create(:name => "Vanuatu", :code => "VU", :status => "1")
# Country.create(:name => "Venezuela, Bolivarian Republic of", :code => "VE", :status => "1")
# Country.create(:name => "Viet Nam", :code => "VN", :status => "1")
# Country.create(:name => "Virgin Islands, British", :code => "VG", :status => "1")
# Country.create(:name => "Virgin Islands, U.S.", :code => "VI", :status => "1")
# Country.create(:name => "Wallis and Futuna", :code => "WF", :status => "1")
# Country.create(:name => "Western Sahara", :code => "EH", :status => "1")
# Country.create(:name => "Yemen", :code => "YE", :status => "1")
# Country.create(:name => "Zambia", :code => "ZM", :status => "1")
# Country.create(:name => "Zimbabwe", :code => "ZW", :status => "1")

#DHL Products
DhlProduct.create(code: '0', name: 'Logistics Services', content_code: 'LOG', doc_or_nondoc: 'A-Not Applicable');
DhlProduct.create(code: '1', name: 'Domestic Express 12:00', content_code: 'DOT', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: '2', name: 'B2C', content_code: 'BTC', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: '3', name: 'B2C', content_code: 'B2C', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: '4', name: 'Jetline', content_code: 'NFO', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: '5', name: 'Sprintline', content_code: 'SPL', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: '7', name: 'Express Easy', content_code: 'XED', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: '8', name: 'Express Easy', content_code: 'XEP', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: '9', name: 'Europack', content_code: 'EPA', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'A', name: 'Auto Reversals', content_code: 'N/A', doc_or_nondoc: 'A-Not Applicable');
DhlProduct.create(code: 'B', name: 'Breakbulk Express', content_code: 'BBX', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'C', name: 'Medical Express', content_code: 'CMX', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'D', name: 'Express Worldwide', content_code: 'DOX', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'E', name: 'Express 9:00', content_code: 'TDE', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'F', name: 'Freight Worldwide', content_code: 'FRT', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'G', name: 'Domestic Economy Select', content_code: 'DES', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'H', name: 'Economy Select', content_code: 'ESI', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'I', name: 'Domestic Express 9:00', content_code: 'DOK', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'J', name: 'Jumbo Box', content_code: 'JBX', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'K', name: 'Express 9:00', content_code: 'TDK', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'L', name: 'Express 10:30', content_code: 'TDL', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'M', name: 'Express 10:30', content_code: 'TDM', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'N', name: 'Domestic Express', content_code: 'DOM', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'O', name: 'Domestic Express 10:30', content_code: 'DOL', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'P', name: 'Express Worldwide', content_code: 'WPX', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'Q', name: 'Medical Express', content_code: 'WMX', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'R', name: 'Globalmail Business', content_code: 'GMB', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'S', name: 'Same Day', content_code: 'SDX', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'T', name: 'Express 12:00', content_code: 'TDT', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'U', name: 'Express Worldwide', content_code: 'ECX', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'V', name: 'Europack', content_code: 'EPP', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'W', name: 'Economy Select', content_code: 'ESU', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'X', name: 'Express Envelope', content_code: 'XPD', doc_or_nondoc: 'Y-Doc');
DhlProduct.create(code: 'Y', name: 'Express 12:00', content_code: 'TDY', doc_or_nondoc: 'N-Non Doc');
DhlProduct.create(code: 'Z', name: 'Destination Charges', content_code: 'N/A', doc_or_nondoc: 'A-Not Applicable');

# DHL Package Types
DhlPackageType.create(code: "BD", name: "Jumbo Document ")
DhlPackageType.create(code: "BP", name: "Jumbo Parcel") 
DhlPackageType.create(code: "CP", name: "Customer-provided")
DhlPackageType.create(code: "DC", name: "Document") 
DhlPackageType.create(code: "DF", name: "DHL Flyer") 
DhlPackageType.create(code: "DM", name: "Domestic") 
DhlPackageType.create(code: "ED", name: "Express Document") 
DhlPackageType.create(code: "EE", name: "DHL Express Envelope") 
DhlPackageType.create(code: "FR", name: "Freight") 
DhlPackageType.create(code: "JB", name: "Jumbo box") 
